### ISSUE TITLE
Will there be work on this plugin?

### ISSUE THREAD

**Issue by siddiquiehtesham** [fastify/fastify-passport#2]

**Comment by Eomm** [comment]
We should check if it is still needed since we have all the standard auth like
https://github.com/fastify/fastify-oauth2
https://github.com/fastify/fastify-auth
https://github.com/fastify/fastify-jwt

In case what you think is missing? Would you like to contribute? 💪

Related to https://github.com/fastify/fastify/issues/1350

**Comment by fox1t** [comment]
I think that having one login fastify plugin that can load login strategies is important in building nice ecosystem for end users. IMHO we absolutely have to build this kind of plugin.

**Comment by mcollina** [comment]
I think so as well :D. We need help to finish off this module.

**Comment by willin** [comment]
is it like express plugin passport?

**Comment by fox1t** [comment]
Hi. I am happy to inform you that I am actively working again on this plugin.

**Comment by siddiquiehtesham** [comment]
That seems to be interesting :)

**Comment by millette** [comment]
FYI: I am also tempted to add oauth using `grant` instead of `passport`: <https://github.com/simov/grant/issues/123>

**Comment by fox1t** [comment]
> FYI: I am also tempted to add oauth using `grant` instead of `passport`: [simov/grant#123](https://github.com/simov/grant/issues/123)

Let me know if you need any help with this. ;)

**Comment by maumercado** [comment]
> Hi. I am happy to inform you that I am actively working again on this plugin.

I would like to help build this, if there's anything I can help with, please let me know.

**Comment by mcollina** [comment]
@fox1t are you still willing to lead this effort? If not, maybe @maumercado might take lead.

**Comment by fox1t** [comment]
Hi. Yes I have a working plugin on my local machine. I think I’ll create a branch and push it there this weekend, so we can work on it together. 
It is ok for you?

**Comment by mcollina** [comment]
Awesome thanks!!

**Comment by fox1t** [comment]
@mcollina sorry for bothering you. What is the best thing to do to share my code here and start discussing about the implementation? A new branch? PR on master? Something completely different?

Thanks in advice.

**Comment by mcollina** [comment]
Either works, as you prefer. A PR might be easier to review.

**Comment by fox1t** [comment]
Hi, I am asking for a help, here!
First of all I apologize for letting in stale this issue. I've been busy lately organizing another OSS huge project.

@maumercado are you still interested in doing this? My approach was to clone original [passport](https://github.com/jaredhanson/passport) and to transform it to a fastify plugin. It worked. 
There were some minor fixable issues due to the fact that passport modifies nodejs' req object: since it is a stream it is pausable. 

I am here to jump in if needed, but I can't organize the work on the plugin at the moment.

I am really sorry for this circumstance and I apologize again! :/

**Comment by mcollina** [comment]
@fox1t would you mind pushing your work so far?

**Comment by fox1t** [comment]
OK, I'll do it!

**Comment by fox1t** [comment]
@mcollina I just pushed the code here. https://github.com/fastify/fastify-passport/tree/init
All tests are missing and some deps are old. In addition to that I think this is a starting point to make code more fastify-like plugin.

**Comment by SerayaEryn** [comment]
I‘d like to help, too. Please let me know if I can help somehow.

**Comment by SerayaEryn** [comment]
I‘ll take a look at the branch and start to work on it.

**Comment by airhorns** [comment]
Did anyone make any progress on this?

**Comment by mcollina** [comment]
Would you like to work on it @airhorns ?

**Comment by airhorns** [comment]
My specific needs are pretty strange sadly. I wish very much there was a docker for OAuth. I found https://github.com/fastify/fastify-passport/pull/3 though which maybe just needs to be pushed over the edge, if I end up going down the passport rabbit hole I'll try to upstream that work.

**Comment by simov** [comment]
:wave: just wanted to let you know that I just released [Grant](https://github.com/simov/grant) v5.4.0 with a plugin for Fastify
