### ISSUE TITLE
Support @fastify/session out of the box

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-passport#319]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

As https://github.com/fastify/session became part of the org, we should list it here as one of the default session manager. I think it would _just_ work, but it still needs tests and docs.

**Comment by sameer-coder** [comment]
I have updated the docs and now working on adding some test cases. Right now  `fastify-secure-session`  is used for building the test server and that is used in all the tests. What would be some good tests to add for testing the integration with `@fastify/session`. I was thinking of only adding some specific tests (maybe related to oauth strategies) instead of duplicating all the existing ones with `@fastify/session`.

**Comment by mcollina** [comment]
PTAL at https://github.com/fastify/fastify-passport/pull/352

**Comment by mcollina** [comment]
Adding new tests is ok.

**Comment by ash0080** [comment]
Please do not, I don't want use any session for a JWT scenario
